--Pregunta 1:
SELECT ID_MODELO_BUS,MODELO,NUMERO_ASIENTOS,CAPACIDAD_DE_PIE,(NUMERO_ASIENTOS+CAPACIDAD_DE_PIE) SALARIO_TOTAL
FROM ET_MODELO_BUS
ORDER BY 5
;
--Pregunta 2:
SELECT ID_BUS,FECHA,SENTIDO,count(*) CANTIDAD
FROM ET_TURNO 
GROUP BY FECHA,SENTIDO,ID_BUS
ORDER BY ID_BUS,FECHA
;
--Pregunta 3:
SELECT b.NOMBRE,
CASE a.ESTADO
    WHEN 'A' THEN 'actualmente se usa'
    WHEN 'B' THEN 'dado de baja'
    WHEN 'T' THEN 'paradero reubicado temporalmente'
    END ESTADO_PARADERO,
count(a.ESTADO)
FROM ET_PARADERO a,ET_DISTRITO b 
WHERE a.id_distrito=b.id_distrito
GROUP BY a.ESTADO,b.NOMBRE
ORDER BY 1,2
;
--Pregunta 4:
SELECT a.ID_BUS,a.FECHA,a.ID_TURNO_VIAJE,
CASE a.SENTIDO
    WHEN 'V' THEN 'Vuelta'
    WHEN 'I' THEN 'Ida'
    END SENTIDO,
SUM(c.PASAJEROS_SUBIDA) CANTIDAD
FROM ET_TURNO a,ET_BUS b,ET_TURNO_PARADERO c
WHERE a.ID_BUS=b.ID_BUS AND a.ID_TURNO_VIAJE=c.ID_TURNO
GROUP BY a.ID_BUS,a.FECHA,a.ID_TURNO_VIAJE,a.SENTIDO
ORDER BY 1
;
--Pregunta 5:
SELECT B.NOMBRE,A.PASAJEROS_SUBIDA,A.PASAJEROS_BAJADA,(A.PASAJEROS_SUBIDA+A.PASAJEROS_BAJADA) TOTAL_PASAJEROS
FROM ET_TURNO_PARADERO A,ET_PARADERO B
WHERE 
    (A.PASAJEROS_SUBIDA+A.PASAJEROS_BAJADA) = 
    (SELECT MAX(A.PASAJEROS_SUBIDA+A.PASAJEROS_BAJADA) TOTAL_PASAJEROS
     FROM ET_TURNO_PARADERO A) AND a.id_paradero=B.ID_PARADERO 
     
GROUP BY B.NOMBRE,A.PASAJEROS_SUBIDA,A.PASAJEROS_BAJADA
;

--Pregunta 6:
SELECT 
CASE T.SENTIDO
	WHEN 'V' THEN 'Vuelta'
    WHEN 'I' THEN 'Ida'
    END SENTIDO,
P.NOMBRE,
CASE P.TIPO
	WHEN 'N' THEN 'Paradero'
    WHEN 'I' THEN 'Inicial'
    WHEN 'F' THEN 'Fin'
    END SENTIDO
FROM ET_TURNO T, ET_TURNO_PARADERO TP, ET_PARADERO P
WHERE 
	T.ID_TURNO_VIAJE = TP.ID_TURNO AND TP.ID_PARADERO = P.ID_PARADERO AND P.ESTADO = 'A'
    AND T.FECHA = (SELECT MAX(FECHA) FROM ET_TURNO A)
ORDER BY T.SENTIDO, P.NOMBRE, P.TIPO
;
--Pregunta 7:
SELECT
    C.ID_CONDUCTOR,
    C.NOMBRES,
    C.APELLIDO_PATERNO,
    C.APELLIDO_MATERNO,
    COUNT(*) AS CANTIDAD_VIAJES
FROM
    ET_CONDUCTOR C
JOIN
    ET_TURNO T ON C.ID_CONDUCTOR = T.ID_CONDUCTOR
WHERE
    T.FECHA BETWEEN CURDATE() - INTERVAL 1 YEAR AND CURDATE()
GROUP BY
    C.ID_CONDUCTOR,
    C.NOMBRES,
    C.APELLIDO_PATERNO,
    C.APELLIDO_MATERNO
ORDER BY
    CANTIDAD_VIAJES DESC
;